### ISSUE TITLE
setBodyWeight error

### ISSUE THREAD

**Issue by johnyphi** [Pythe1337N/garmin-connect#36]
When invoking setBodyWeight I get the following

TypeError: Cannot destructure property 'body' of '(intermediate value)' as it is undefined.
    at CFClient.putJson (F:\dotnet.garmin.connect-main\dotnet.garmin.connect-main\Garmin.Connect.NodeJS\node_modules\garmin-connect\dist\common\CFClient.js:135:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GarminConnect.put (F:\dotnet.garmin.connect-main\dotnet.garmin.connect-main\Garmin.Connect.NodeJS\node_modules\garmin-connect\dist\garmin\GarminConnect.js:431:26)
    at async main (F:\dotnet.garmin.connect-main\dotnet.garmin.connect-main\Garmin.Connect.NodeJS\app.js:13:5)
PS F:\dotnet.garmin.connect-main\dotnet.garmin.connect-main\Garmin.Connect.NodeJS> node app.js
F:\dotnet.garmin.connect-main\dotnet.garmin.connect-main\Garmin.Connect.NodeJS\node_modules\garmin-connect\dist\common\CFClient.js:135
        const { body } = await this.scraper(options);
                ^

I've installed the package using npm. Calling code is pretty simple, see below. Any assistance greatly appriciated.

const { GarminConnect } = require('garmin-connect');

// Has to be run in an async function to be able to use the await keyword
const main = async () => {
    // Create a new Garmin Connect Client
    const GCClient = new GarminConnect();

    // Uses credentials from garmin.config.json or uses supplied params
    await GCClient.login('myrealemail', 'myrealpassword');

    // Get user info
    await GCClient.setBodyWeight(80.0);

    // Log info to make sure signin was successful
    console.log(info);
};

// Run the code
main();

**Comment by Pythe1337N** [comment]
https://github.com/codemanki/cloudscraper/issues/194
This seems to be related
